//
// Created by kana on 7/13/23.
//

#ifndef LINUX_KERNEL_CONFIG_H
#define LINUX_KERNEL_CONFIG_H

#define PEACHOS_TOTAL_INTERRUPTS    512

#define KERNEL_CODE_SELECTOR        0x08
#define KERNEL_DATA_SELECTOR        0x10


// 100MB heap size
#define PEACHOS_HEAP_SIZE_BYTES           104857600
#define PEACHOS_HEAP_BLOCK_SIZE_BYTES     4096
#define PEACHOS_HEAP_ADDRESS              0x01000000
#define PEACHOS_HEAP_TABLE_ADDESS         0x00007E00

#define PEACHOS_SECTOR_SIZE     512


#endif //LINUX_KERNEL_CONFIG_H
